export const meta = {
  name: 's-machines-stage3-design',
  description: 'Step-level design plus adversarial verification of the Stage 3 TileEntityMekanism base-split (energy-only real tile on both loaders). Lands no code.',
  phases: [
    { title: 'Scout', detail: 'deep digs into the base-split mechanics' },
    { title: 'Design', detail: 'coordinated base-split sub-stages' },
    { title: 'Verify', detail: '3 adversarial lenses' },
  ],
}

const CTX = [
  'REPO: /Users/goddv/Development/Mekanism-Fabric (Mekanism fork, MC 26.1 deobfuscated vanilla names, no remap, Architectury multi-loader).',
  'MODULES: common/src/main/java is loader-neutral and compiles against VANILLA MC only (no net.neoforged / net.fabricmc / dev.architectury imports, and no class that lives only under neoforge/src). neoforge/src/{main,api,generators,additions,tools,datagen}/java is NeoForge. fabric/src/main/java is Fabric.',
  'MANDATE: NeoForge stays BYTE-IDENTICAL and behaviorally identical (the user tests it in-game). Tile NBT and data components are SAVED and SYNCED, so NBT keys/order/codecs and capability exposure identity are load-bearing. Fabric is the port target.',
  'READ docs/MACHINE_ENDGAME_ROADMAP.md (8-stage plan; this task is Stage 3) and docs/REGISTRATION_GATE_PLAN.md.',
  'HOUSE PATTERNS: same-FQN git mv hoist; *Base split (Base class in :common holding the loader-clean members, neoforge subclass extends it, package-private/protected Base ctor, callers untouched) used for BlockMekanism->BlockMekanismBase and BlockType->BlockTypeBase; service seam interface with INSTANCE = MekanismAPIBase.getService plus META-INF/services descriptors in BOTH loaders (precedents ITileSyncService, ITileSoundService just added, ICapabilityExposureService, IBlockSecurityUtils, IRadiationManager); access-widener line in fabric/src/main/resources/mekanism.accesswidener for vanilla members NeoForge AT-widens (works for methods and fields).',
  'HIDDEN COUPLING WARNING: NeoForge patches vanilla classes inside the net.minecraft namespace (extra method overloads like BlockState.getFriction, coadded classes like GuiGraphicsExtractor). Import scans miss these; only the compile gate catches them. The vanilla jar for javap is at ~/.gradle/caches/fabric-loom/26.1.2/minecraft-merged.jar.',
  'GROUND TRUTH (verified): TileEntityMekanism at neoforge/src/main/java/mekanism/common/tile/base/TileEntityMekanism.java (~1617 lines) has ZERO net.neoforged imports and, after the Stage 1 ITileSoundService seam, ZERO net.minecraft.client imports. Its base chain is TileEntityUpdateable (already :common) then CapabilityTileEntity (neoforge-only; holds 5 HandlerManager fields plus NeoForge BlockCapability/BlockCapabilityCache/ICapabilityProvider/FluidStack) then TileEntityMekanism. A same-FQN hoist is impossible (a :common class cannot extend a neoforge superclass), so this needs a BASE-SPLIT.',
  'ENTANGLEMENT (verified): MachineEnergyContainer references TileEntityMekanism/TileEntityFactory/TileEntityProgressMachine (circular with the tile). Tile-components TileComponentSecurity/Upgrade/Frequency/Config each reference TileEntityMekanism plus MekanismContainer plus MekanismDataComponents plus SecurityMode. SecurityMode and RedstoneControl enums implement IHasEnumNameTextComponent, which extends net.neoforged.neoforge.common.TranslatableEnum (a real NeoForge coupling). ContainerType.TYPES is iterated at 5 sites in the tile: loadAdditional, saveAdditional, applyImplicitComponents, getRemapEntries, collectImplicitComponents, and is NeoForge-capability-bound. SyncMapper extends BaseAnnotationScanner over neoforgespi ModFileScanData.',
  'FABRIC FOOTHOLD: fabric content/machine FabricRealMachines + MachineBlock + MachineBlockEntity register 5 real machine blocks via the :common MekanismBlockRegister but use a SIMPLIFIED demo block-entity (not the real tile). Energy/heat/recipe/auto-io Fabric self-tests PASS. Capability exposure is already seamed (ICapabilityExposureService); Fabric energy uses MekanismFabricEnergy BlockApiLookup.',
  'GOAL (Stage 3): get a REAL TileEntityMekanism-derived tile storing and exposing ENERGY on BOTH loaders (no recipe, no GUI) by base-splitting TileEntityMekanism into a :common TileEntityMekanismBase (the ~1600 loader-clean lines) plus a neoforge layer holding the CapabilityTileEntity machinery and the ContainerType.TYPES handling. Hardest, riskiest refactor in the port; it WILL need the user in-game NeoForge test. Produce a correct, step-level, sub-staged plan; each sub-stage independently green and NeoForge byte-identical or clearly flagged. Be honest if the minimal energy-only cut needs prerequisite slices (TranslatableEnum resolution, MekanismContainer deferral, SecurityMode, MekanismDataComponents) and sequence them.',
].join('\n')

const SCOUT = { type:'object', required:['summary','findings','classification','risks'], properties:{
  summary:{type:'string'},
  findings:{type:'array', items:{type:'object', required:['topic','detail'], properties:{topic:{type:'string'}, detail:{type:'string'}}}},
  classification:{type:'array', items:{type:'object', required:['name','verdict','why'], properties:{name:{type:'string'}, verdict:{type:'string', enum:['hoist-with-core','seam','base-split','keep-neoforge-residue','prerequisite-slice','already-common','defer','n/a']}, why:{type:'string'}}}},
  risks:{type:'array', items:{type:'string'}},
}}
const DESIGN = { type:'object', required:['overview','feasibilityVerdict','subStages','firstSubStageDetail','capabilitySplitMechanics','neoforgeIdentityArgument','prerequisites','risks'], properties:{
  overview:{type:'string'},
  feasibilityVerdict:{type:'string'},
  subStages:{type:'array', items:{type:'object', required:['n','title','goal','keyMoves','greenGate','neoforgeRisk'], properties:{n:{type:'number'}, title:{type:'string'}, goal:{type:'string'}, keyMoves:{type:'string'}, greenGate:{type:'string'}, neoforgeRisk:{type:'string', enum:['none-byte-identical','low','medium','high-needs-ingame-test']}}}},
  firstSubStageDetail:{type:'array', items:{type:'object', required:['n','title','detail','files'], properties:{n:{type:'number'}, title:{type:'string'}, detail:{type:'string'}, files:{type:'array', items:{type:'string'}}}}},
  capabilitySplitMechanics:{type:'string'},
  neoforgeIdentityArgument:{type:'string'},
  prerequisites:{type:'array', items:{type:'string'}},
  risks:{type:'array', items:{type:'string'}},
}}
const VERDICT = { type:'object', required:['lens','verdict','defects','notes'], properties:{
  lens:{type:'string'},
  verdict:{type:'string', enum:['sound','sound-with-fixes','defective']},
  defects:{type:'array', items:{type:'object', required:['severity','title','detail','fix'], properties:{severity:{type:'string', enum:['fatal','major','minor']}, title:{type:'string'}, detail:{type:'string'}, fix:{type:'string'}}}},
  notes:{type:'string'},
}}

phase('Scout')
log('Deep-digging the base-split mechanics')
const sc = await parallel([
  () => agent(CTX + '\n\nTASK S1 - CapabilityTileEntity + base-split hierarchy. Read CapabilityTileEntity.java fully and TileEntityUpdateable. List CapabilityTileEntity fields/methods (the 5 HandlerManager, BlockCapabilityCache, cap-exposure, collect/apply component methods) and its net.neoforged surface. Work out the EXACT base-split hierarchy that compiles AND preserves identity: can :common TileEntityMekanismBase sit between TileEntityUpdateable and CapabilityTileEntity (so CapabilityTileEntity extends TileEntityMekanismBase and the tile extends CapabilityTileEntity), or must the base sit elsewhere? Give the exact extends chain and, for each of the 5 HandlerManager fields the ~1600 lines use, the exact mechanism by which :common code reaches them (protected abstract getter, pulled-up protected field, or seam).', { label:'scout:cap-split', phase:'Scout', schema:SCOUT }),
  () => agent(CTX + '\n\nTASK S2 - ContainerType.TYPES + the 5 save/load/data-component methods. Read loadAdditional, saveAdditional, applyImplicitComponents, getRemapEntries, collectImplicitComponents in TileEntityMekanism and ContainerType.java. Quote what each does with ContainerType.TYPES + ItemCapability/ItemAccess/DeferredHolder. For each of the 5, give the split mechanic to keep it on the neoforge layer while the rest of the tile logic moves to :common (keep-on-residue-as-override calling a :common super, protected hook, or seam). Confirm NBT/data-component identity is preserved (same keys, order, codecs).', { label:'scout:containertype', phase:'Scout', schema:SCOUT }),
  () => agent(CTX + '\n\nTASK S3 - The TranslatableEnum coupling (blocks SecurityMode/RedstoneControl + many enums). Read IHasEnumNameTextComponent.java and IHasTextComponent. grep the whole tree for TranslatableEnum and IHasEnumNameTextComponent usage: who CONSUMES it (instanceof, NeoForge ModConfigSpec EnumValue translation, getTranslatedName callers)? Are RedstoneControl/SecurityMode actually used in NeoForge ModConfigSpec configs (where TranslatableEnum matters) or only as NBT/synced tile fields (where it is vestigial)? Determine the SAFEST byte-identical way to make IHasEnumNameTextComponent loader-neutral: (a) move to :common dropping the TranslatableEnum extends if nothing relies on it; (b) a NeoForge bridge interface; (c) leave it neoforge and have the enums implement the :common IHasTextComponent only. Give evidence. List how many Mekanism enums implement it (blast radius).', { label:'scout:translatable-enum', phase:'Scout', schema:SCOUT }),
  () => agent(CTX + '\n\nTASK S4 - Energy-only minimal closure. In TileEntityMekanism separate the members the ENERGY path needs (energy container holder, MachineEnergyContainer wiring, energy cap exposure, basic tick/active/save) from recipe/GUI/security/upgrade/config/redstone/comparator members an energy-only tile can stub or keep-if-clean. MachineEnergyContainer is circular with the tile (refs TileEntityMekanism/TileEntityFactory/TileEntityProgressMachine): does it move with the base, do TileEntityFactory/TileEntityProgressMachine have to move too, or can the circular refs be narrowed to an interface? Quote. Are the tile-components (Security/Upgrade/Frequency/Config) instantiated unconditionally or only for machines that opt in? Determine the minimal component set for a bare energy tile.', { label:'scout:energy-closure', phase:'Scout', schema:SCOUT }),
  () => agent(CTX + '\n\nTASK S5 - Are MekanismContainer / SyncMapper / MekanismDataComponents hard prerequisites for an energy-only tile or deferrable? Does an energy-only tile (no GUI) reference MekanismContainer at all, or only machines with a GUI? Trace it. Where is SyncMapper invoked from the tile path; is it on the energy-only critical path or only container-sync; can it be seamed or deferred? Do the energy-only tile-components reference MekanismDataComponents, and if so which components and are their payloads loader-clean? Bottom line: list the HARD prerequisites for a bare energy-only TileEntityMekanismBase vs the deferrable subsystems. This decides whether Stage 3 is one coordinated cut or needs prerequisite slices first.', { label:'scout:container-deferral', phase:'Scout', schema:SCOUT }),
])
if (sc.some(x => !x)) { log('scout failure'); return { error:'scout', scouts: sc } }

phase('Design')
log('Designing the coordinated base-split sub-stages')
const design = await agent(CTX + '\n\nYou are the DESIGNER for the Stage 3 TileEntityMekanismBase base-split. Scout reports follow. Produce: feasibilityVerdict (can an energy-only base-split land near-term as a coordinated cut, or does it need prerequisite slices first - honest); capabilitySplitMechanics (the EXACT compilable hierarchy + how the 5 HandlerManager fields and the 5 ContainerType.TYPES methods stay on the neoforge layer while ~1600 lines move to :common); subStages (ordered, each independently green and byte-identical-or-flagged, including any prerequisite slices like the TranslatableEnum resolution as early sub-stages); firstSubStageDetail (exact implementable steps with files + code sketches; must be green-able and byte-identical-or-flagged); prerequisites; neoforgeIdentityArgument (esp NBT/data-component/capability identity); risks. Read files to confirm; do not hand-wave. Scouts: S1=' + JSON.stringify(sc[0]) + ' S2=' + JSON.stringify(sc[1]) + ' S3=' + JSON.stringify(sc[2]) + ' S4=' + JSON.stringify(sc[3]) + ' S5=' + JSON.stringify(sc[4]), { label:'design:stage3', phase:'Design', schema:DESIGN })
if (!design) { log('design failure'); return { error:'design', scouts: sc } }

phase('Verify')
log('Adversarial verification')
const vd = await parallel([
  () => agent(CTX + '\n\nADVERSARIAL VERIFIER lens BASE-SPLIT MECHANICS + NEOFORGE IDENTITY. Try to REFUTE that capabilitySplitMechanics compiles AND preserves NeoForge tile NBT/capability/data-component identity. Read CapabilityTileEntity, the 5 ContainerType.TYPES methods, and the tile save/load. Hunt: a hierarchy inversion that does not compile (a :common base referencing a neoforge field/type), an NBT key/order/codec change, a capability-exposure timing change, a visibility trap, ContainerType.TYPES iteration leaking into :common (would need ContainerType in :common = fatal), any saved-state divergence. Default defective if any save/sync identity is uncertain. DESIGN: ' + JSON.stringify(design), { label:'verify:mechanics', phase:'Verify', schema:VERDICT }),
  () => agent(CTX + '\n\nADVERSARIAL VERIFIER lens FIRST SUB-STAGE COMPILE-FEASIBILITY + TranslatableEnum. Try to REFUTE that firstSubStageDetail is green-able and that the TranslatableEnum resolution is byte-identical on NeoForge. Does dropping/replacing the TranslatableEnum extends change ANY NeoForge behavior (config GUI enum translation, instanceof)? javap-confirm vanilla signatures for anything moved to :common. Check first-sub-stage files for hidden net.minecraft-patch coupling. If TranslatableEnum cannot be made loader-neutral byte-identically, say why + the correct fix. DESIGN: ' + JSON.stringify(design), { label:'verify:firststage-enum', phase:'Verify', schema:VERDICT }),
  () => agent(CTX + '\n\nADVERSARIAL VERIFIER lens PREREQUISITE COMPLETENESS + SCOPE. Try to REFUTE the feasibilityVerdict + subStage sequencing. Hunt: a sub-stage claimed green that needs a deferred subsystem (MekanismContainer/SecurityMode/MekanismDataComponents/SyncMapper) still in neoforge; the circular MachineEnergyContainer not actually resolved; an energy-only tile that secretly still instantiates security/upgrade components; underestimated prerequisite count. Be the realist: if the energy-only tile is N sub-stages and K prerequisite slices, state which and the rough effort. DESIGN: ' + JSON.stringify(design), { label:'verify:prereq-scope', phase:'Verify', schema:VERDICT }),
])
return { design, verdicts: { mechanics:vd[0], firstStageEnum:vd[1], prereqScope:vd[2] }, scouts: { s1:sc[0], s2:sc[1], s3:sc[2], s4:sc[3], s5:sc[4] } }
